sudo: required

language: java

jdk: openjdk8

services:
  - docker

env:
  - SGT_VER=2.4.2 PROFILE=singularity TOOL_INSTALL=all NXF_VER=0.27.6
  - SGT_VER=2.4.2 PROFILE=singularity TOOL_INSTALL=all
  - PROFILE=docker TOOL_INSTALL=nextflow NXF_VER=0.27.6
  - PROFILE=docker TOOL_INSTALL=nextflow

install: # Install Nextflow (and Singularity if needed)
  - "./tests/install.sh --tool $TOOL_INSTALL"
  - cd ${TRAVIS_BUILD_DIR}/tests/
  - mkdir results

script: "./container_test_hisat.sh -p $PROFILE"
