sudo: required
language: python
jdk: openjdk8
services:
  - docker
python:
  - "3.6"
cache: pip
matrix:
  fast_finish: true

env:
  - FLAGS="-a star" INST=nt NXF_VER=0.27.6
  - FLAGS="-a star" INST=nt
  - FLAGS="-a star -s" INST=nts
  - FLAGS="-a hisat2" INST=nt NXF_VER=0.27.6
  - FLAGS="-a hisat2" INST=nt
  - FLAGS="-a hisat2 -s" INST=nts

install: # Install Singularity if needed
  - "./tests/install.sh $INST"
  - "cd ${TRAVIS_BUILD_DIR}/tests/"

script:
  - "nf-core lint $TRAVIS_BUILD_DIR"
  - "./run_test.sh $FLAGS -b"
  - "./run_test.sh $FLAGS"
