sudo: required
language: python
jdk: openjdk8
services:
  - docker
python:
  - "3.6"
cache: pip
matrix:
  fast_finish: true

env:
  - T=nt  FL="-a star" NXF_VER=0.27.6
  - T=nt  FL="-a star"
  - T=nts FL="-a star -s"
  - T=nt  FL="-a hisat2" NXF_VER=0.27.6
  - T=nt  FL="-a hisat2"
  - T=nts FL="-a hisat2 -s"

install:
  - "./tests/install.sh $T"
  - "cd ${TRAVIS_BUILD_DIR}/tests/"

script:
  - "nf-core lint ${TRAVIS_BUILD_DIR}"
  - "SECONDS=0 && travis_wait 50 ./run_test.sh ${FL} -b"
  - 'echo "Test run took $(($SECONDS / 60)) minutes and $(($SECONDS % 60)) seconds."'
  - "SECONDS=0 && travis_wait 50 ./run_test.sh ${FL}"
  - 'echo "Test run took $(($SECONDS / 60)) minutes and $(($SECONDS % 60)) seconds."'
  - "find results/" # Print results files
