sudo: required
language: python
services:
  - docker
jdk: openjdk8
python: "3.6"
node_js: "node"
cache: pip
matrix:
  fast_finish: true

env:
  - T=nt  FL="-a star" NXF_VER=0.27.6
  - T=nt  FL="-a star"
  - T=nts FL="-a star -s"
  - T=nt  FL="-a hisat2" NXF_VER=0.27.6
  - T=nt  FL="-a hisat2"
  - T=nts FL="-a hisat2 -s"

install:
  - "./tests/install.sh $T"
  - "npm install -g gnomon"
  - "cd ${TRAVIS_BUILD_DIR}/tests/"

script:
  - "nf-core lint ${TRAVIS_BUILD_DIR}"
  - "./run_test.sh ${FL} -b | gnomon --medium 120.0 --high 600.0 --real-time=false"
  - "find results/" # Print results files
