# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: ngi-rnaseq
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  # Default bismark
  - conda-forge::openjdk # Needed for FastQC docker - see bioconda/bioconda-recipes#5026
  - fastqc=0.11.7
  - trim-galore=0.4.5
  - star=2.5.4a
  - hisat2=2.1.0
  - picard=2.18.0
  - bioconductor-dupradar=1.8.0
  - bioconductor-edger=3.20.7
  - preseq=2.0.2
  - rseqc=2.6.4
  - samtools=1.7
  - stringtie=1.3.3
  - subread=1.6.0
  - multiqc=1.5
